project:
  type: website
  output-dir: docs
  resources:
    - Assets

website:
  title: "ECON-R"

  navbar:
    logo: Assets/logo-econr.svg
    left:
      - href: index.qmd
        text: Beranda

      - text: MatKul Dasar IE
        menu:
          - href: lessons/lesson-1-introduction-to-economics-and-r.qmd
            text: Lesson 1
          - href: lessons/lesson-2-supply-and-demand.qmd
            text: Lesson 2
          - href: lessons/lesson-3-market-equilibrium.qmd
            text: Lesson 3
          - href: lessons/lesson-4-elasticity-of-demand.qmd
            text: Lesson 4
          - href: lessons/lesson-5-gdp-and-economic-growth.qmd
            text: Lesson 5
          - href: lessons/lesson-6-inflation-and-cpi.qmd
            text: Lesson 6

      - href: thewikenpro.qmd
        text: The Wiken Project

      - href: belajar.qmd
        text: BelajaR

      - href: mailme.qmd
        text: Mail.me

format:
  html:
    css: styles.css
    google-analytics: "G-KP8JERTSJ1"
    include-in-header: 
    - gsc.html
